export const FAMILY_STATE = {
  free: 'Свободна',
  all_complicated: 'Всё сложно',
};

export const SPORT_STATE = {
  life_in: 'Абсолютно люблю',
  walking: 'Хожу пешком',
  keep_in_shape: 'Держу форму',
};

export const DATE_TARGET_STATE = {
  serious_date: 'Серьёзные отношения',
  conversation: 'Дружеское общение',
  new_experience: 'Новый опыт',
};

export const ZODIAC_SIGN_STATE = {
  sagittarius: 'Стрелец',
  capricornus: 'Козерог',
  pisces: 'Рыбы',
  taurus: 'Телец',
  aquarius: 'Водолей',
  libra: 'Весы',
  leo: 'Лев',
  gemini: 'Близнецы',
  virgo: 'Дева',
  cancer: 'Рак',
  aries: 'Овен',
  scorpius: 'Скорпион',
};

// todo добавить иконки из вк
export const INTERESTS_STATE = {
  cooking: 'кулинария',
  singing: 'пение',
  sushi: 'суши',
  concert_and_show: 'концерты и шоу',
  dogs: 'собаки',
  cats: 'котики',
  dancing: 'танцы',
  horrors: 'хорроры',
  photo: 'фото',
  music: 'музыка',
  pizza: 'пицца',
  movies: 'фильмы',
  travel: 'путешествия',
  fitness_gym: 'фитнес',
  restaurants: 'рестораны',
  camping: 'кемпинг',
  art: 'искусство',
  country_trips: 'отдых на природе',
  books: 'книги',
  tea: 'чай',
  music_lover: 'меломан',
  yoga: 'йога',
  sweets: 'сладости',
  active_leisure: 'активный отдых',
  shopping: 'шоппинг',
  fashion: 'мода',
  makeup: 'мейкап',
  friends: 'встречи с друзьями',
  theater: 'театр',
  beach_rest: 'отдых на пляже',
  comedies: 'комедии',
  events: 'разные мероприятия',
  bicycle: 'велосипед',
  adventures: 'приключения',
  cars: 'машины',
  coffee: 'кофе',
  mountains: 'горы',
  rock: 'рок',
  home_cooking: 'домашняя еда',
  parties_and_clubs: 'тусовки и клубы',
  volleyball: 'воллейбол',
  painting: 'рисование',
  design: 'дизайнинг',
  bakery: 'выпечка',
  museums_and_galleries: 'музеи и галереи',
  videography: 'видеомонтаж',
  computer_games: 'компьютерные игры',
  gaming: 'гейминг',
  thrillers: 'триллеры',
  gymnastic: 'гимнастика',
  burger: 'бургеры',
  festivals: 'фестивали',
  boardgames: 'настолки',
  detectives: 'детективы',
  blogging: 'блоггинг',
  healthy_diet: 'здоровая еда',
  pilates: 'пилатес',
  tourism: 'туризм',
  run: 'бег',
  rap: 'рэп',
  skateboard: 'скейтборд',
  vegetarianism: 'вегетарианство',
  cartoons: 'мультики',
  handmade: 'рукоделие',
  cinema: 'кинотеатр',
  melodramas: 'мелодрамы',
  swimming: 'плавание',
  it: 'IT',
};
