export const FAMILY_STATE = {
  free: 'Свободна',
  all_complicated: 'Всё сложно',
  in_relations: 'В отношениях',
  free_date: 'Свободные отношения',
};

export const SPORT_STATE = {
  not_like: 'Не люблю',
  life_in: 'Абсолютно люблю',
  walking: 'Хожу пешком',
  keep_in_shape: 'Держу форму',
};

export const DATE_TARGET_STATE = {
  serious_date: 'Серьёзные отношения',
  conversation: 'Дружеское общение',
  new_experience: 'Новый опыт',
};

export const ZODIAC_SIGN_STATE = {
  sagittarius: 'Стрелец',
  capricornus: 'Козерог',
  pisces: 'Рыбы',
  taurus: 'Телец',
  aquarius: 'Водолей',
  libra: 'Весы',
  leo: 'Лев',
  gemini: 'Близнецы',
  virgo: 'Дева',
  cancer: 'Рак',
  aries: 'Овен',
  scorpius: 'Скорпион',
};

// todo добавить иконки из вк
export const INTERESTS_STATE = {
  // занятия
  cooking: 'кулинария',
  singing: 'пение',
  dancing: 'танцы',
  camping: 'кемпинг',
  painting: 'рисование',
  shopping: 'шоппинг',
  gaming: 'гейминг',
  blogging: 'блоггинг',
  swimming: 'плавание',
  horse_riding: 'верховая езда',
  ski: 'лыжи',
  gardening: 'садоводство',
  volunteering: 'волонтерство',
  weightlifting: 'пауэрлифтинг',
  // еда
  sushi: 'суши',
  pizza: 'пицца',
  tea: 'чай',
  coffee: 'кофе',
  sweets: 'сладости',
  home_cooking: 'домашняя еда',
  bakery: 'выпечка',
  burger: 'бургеры',
  // животные
  dogs: 'собаки',
  cats: 'котики',
  snakes: 'змеи',
  rabbits: 'кролики',
  hamsters: 'хомячки',
  // мероприятия
  // места
  fitness_gym: 'спортзал',
  restaurants: 'рестораны',
  country_trips: 'отдых на природе',
  active_leisure: 'активный отдых',
  friends: 'встречи с друзьями',
  theater: 'театр',
  beach_rest: 'отдых на пляже',
  events: 'разные мероприятия',
  adventures: 'приключения',
  mountains: 'горы',
  concert_and_show: 'концерты и шоу',
  parties_and_clubs: 'тусовки и клубы',
  museums_and_galleries: 'музеи и галереи',
  festivals: 'фестивали',
  cinema: 'кинотеатр',
  // музыка и жанры
  rock: 'рок',
  rap: 'рэп',
  hip_hop: 'хип хоп',
  pop_music: 'поп (жанр)',
  horrors: 'хорроры',
  comedies: 'комедии',
  thrillers: 'триллеры',
  detectives: 'детективы',
  melodramas: 'мелодрамы',
  dramas: 'драмы',
  classical_music: 'классическая музыка',
  action_movie: 'боевики',
  historical_films: 'исторические фильмы',
  // раздел "люблю"
  movies: 'фильмы',
  art: 'искусство',
  books: 'книги',
  yoga: 'йога',
  fashion: 'мода',
  football: 'футбол',
  volleyball: 'воллейбол',
  basketball: 'баскетбол',
  makeup: 'мейкап',
  bicycle: 'велосипед',
  cars: 'машины',
  design: 'дизайнинг',
  videography: 'видеомонтаж',
  computer_games: 'компьютерные игры',
  photo: 'фотографии',
  music: 'музыка',
  travel: 'путешествия',
  gymnastic: 'гимнастика',
  boardgames: 'настолки',
  healthy_diet: 'здоровая еда',
  pilates: 'пилатес',
  tourism: 'туризм',
  run: 'бег',
  skateboard: 'скейтборд',
  vegetarianism: 'вегетарианство',
  cartoons: 'мультики',
  handmade: 'рукоделие',
  it: 'IT',
  biking: 'мотоциклы',
  scooter: 'скутеры',
  birds: 'птицы',
  roller_skates: 'езда на роликах',

  // кто я?
  music_lover: 'меломан',
};
